status = [ "continuous-integration/jenkins/branch" ]
pr_status = [ "DCO" ]
required_approvals = 1
block_labels = [ "do not merge" ]
delete_merged_branches = true
timeout_sec = 3600 # 1 hour

[committer]
name = "oe-bors[bot]"
email = "oeciteam@microsoft.com"